### ISSUE TITLE
[公平性问题]用户使用异步方法或在事件上注册方法导致即时不准

### ISSUE THREAD

**Issue by simonmysun** [simonmysun/AICLASH#10]
需挂起用户线程或屏蔽掉异步方法和在事件上注册的方法。
- http://dev.w3.org/html5/workers/
- https://developer.mozilla.org/en-US/docs/Web/API/Worker
- https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/basic_usage
- https://developer.mozilla.org/en-US/docs/Web/API/Worker/Functions_and_classes_available_to_workers
- https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope

**Comment by simonmysun** [comment]
for in 这样, 执行 `for(var x in this){this[x]=null;}` 不会影响到标准库和浏览器对象, 但是 `this.XMLHttpRequest = null` 可以

**Comment by D6C92FE5** [comment]
因为属性 `XMLHttpRequest` 是**不可枚举**的
```JavaScript
this.propertyIsEnumerable('XMLHttpRequest') === false
```
如果希望枚举所有属性（而不只是**可枚举**的属性），可以使用 [`.getOwnPropertyNames`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames) 方法
```JavaScript
for (var x in Object.getOwnPropertyNames(this) { ... }
```
扩展阅读：[Enumerability and ownership of properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties)

**Comment by simonmysun** [comment]
原来是这样, 谢谢了! 

不过这样的话, 为什么 setTimeout 之类的又没有被枚举出来呢?

**Comment by D6C92FE5** [comment]
不客气～
因为（目测）大部分原生方法都是不可枚举的吧

**Comment by D6C92FE5** [comment]
不客气～

因为 `setTimeout` 定义在了 `Window` 的原型上 :joy:
```JavaScript
Object.getOwnPropertyNames(this.__proto__).indexOf('setTimeout') == 113
```
其实你可以考虑把 `this.__proto__` 整个抹掉 :joy:

**Comment by simonmysun** [comment]
哈哈, 看来应该这样写: 

    (function(o) {
        if(o === null) {
            return null;
        }
        return Object.getOwnPropertyNames(o).concat(arguments.callee(o.__proto__));
    })(this).map(function(x) {
        this[x]=null;
    });
